services:
  flask-api:
    build: .
    container_name: flask_api
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    networks:
      - app_network

  telegram-bot:
    build: .
    container_name: telegram_bot
    command: ["python", "bot.py"]
    depends_on:
      - flask-api
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
      - ADMIN_IDS=${ADMIN_IDS}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
